### ISSUE TITLE
Exception on change.GitPoller on Windows

### ISSUE THREAD

**Issue by jacky-chuang** [buildbot/buildbot#3375]
Hi,

I use Buildbot ( 0.9.8 ) and Twisted (==17.5.0) to run git poller. Config is below.

```
   c['change_source'].append(changes.GitPoller(
    repourl='git@172.23.45.81:/home/git/201701_postrack_swfw_app', branch='master',pollinterval=300, pollAtLaunch=True,
    gitbin="C:\\Program Files\\Git\\cmd\\git.exe",
    encoding="big5"))
```

   But it always to get the following exception :
  Can anybody tell what’s going wrong ? thanks!

  Jacky
```
2017-06-26 11:49:08+0800 [-] while polling for changes
Traceback (most recent call last):
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
--- ---
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\buildbot\changes\gitpoller.py", line 190, in poll
    path=self.workdir)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\buildbot\changes\gitpoller.py", line 357, in _dovccmd
    path=encodeArg(path), env=os.environ)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\utils.py", line 174, in getProcessOutputAndValue
    reactor)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\utils.py", line 28, in _callProtocolWithDeferred
    reactor.spawnProcess(p, executable, (executable,)+tuple(args), env, path)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
    return Process(self, processProtocol, executable, args, env, path)
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet_dumbwin32proc.py", line 217, in init
    doCreate()
  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet_dumbwin32proc.py", line 214, in doCreate
    command, cmdline, None, None, 1, flags, env, path, StartupInfo)
builtins.TypeError: Objects of type 'bytes' can not be converted to Unicode.
```

**Comment by seankelly** [comment]
What version of Python?

**Comment by jacky-chuang** [comment]
Python 3.6.1

**Comment by rodrigc** [comment]
Fix for this is here: https://github.com/buildbot/buildbot/pull/3368

**Comment by rodrigc** [comment]
Fixed in https://github.com/buildbot/buildbot/pull/3368

**Comment by jacky-chuang** [comment]
I have tried merged master/buildbot/changes/gitpoller.py for #3368 .
But the exception still occured!

**Comment by rodrigc** [comment]
I think this might be a bug in Twisted on Windows.

Can you modify the code in Twisted so that:

```
        def doCreate():
            flags = win32con.CREATE_NO_WINDOW
            self.hProcess, self.hThread, self.pid, dwTid = win32process.CreateProcess(
                command, cmdline, None, None, 1, flags, env, path, StartupInfo)
```

is:

```
        def doCreate():
            flags = win32con.CREATE_NO_WINDOW
            print("command: {} {}".format(command, type(command))
            print("command: {} {}".format(cmdline, type(cmdline))
            print("command: {} {}".format(flags, type(flags))
            print("command: {} {}".format(env, type(env))
            print("command: {} {}".format(path, type(path))
            print("command: {} {}".format(StartupInfo, type(StartupInfo))
            self.hProcess, self.hThread, self.pid, dwTid = win32process.CreateProcess(
                command, cmdline, None, None, 1, flags, env, path, StartupInfo)
```

**Comment by rodrigc** [comment]
@jacky-chuang I just set up a buildbot under Windows, and used Python 3.6.1 and Git.
I cannot reproduce the problem.
Can you provide more details from your master.cfg?

**Comment by rodrigc** [comment]
OK, I was able to reproduce the problem.

**Comment by rodrigc** [comment]
Twisted fix posted here:
https://github.com/twisted/twisted/pull/828

**Comment by jacky-chuang** [comment]
thanks!, after applying twisted/twisted#828, the exception fixed
