### ISSUE TITLE
Current documentation web site is still 3.6, not 3.8

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbot/buildbot#6794]
At present, 0100 UTC Jan 28, https://docs.buildbot.net/current is still showing the 3.6 documentation, not the 3.7.0 documentation, almost two months after the 3.7 release.

**Comment by pmisik** [comment]
To me it is unclear what exactly the problem you report is.
Is it the fact that generated documentation on `https://docs.buildbot.net/current/` says `This is the Buildbot documentation for  Buildbot version 3.6.0.` ? Are you complaining about `3.6.0` here ?

In this case I think it is maintainers decision what is the minimum supported python version. I guess they will always want to keep broadest possible despite python support is not available.

Are you speaking here about the `master` or about `worke`r?
In case of worker I assume maintainers want explicitly  keep support as long as possible.

**Comment by YngveNPettersen** [comment]
This is a scrennshot of the issue
![image](https://user-images.githubusercontent.com/3061808/216703858-bc2348e3-118a-4f9b-8f9b-e9e7d497036c.png)

The version below "Buildbot" should be 3.7.0

**Comment by pmisik** [comment]
@YngveNPettersen Thank You for Your reply.
I want to apologize You and maintainers for mine unnecessary comment on this issue. 
I did not properely compared url @YngveNPettersen specified (as issue reporter) against mine buildbot bookmarks.
So I was confused.
My favorite buildbot documentation bookmark pointed to https://buildbot.readthedocs.io/en/stable/ , where I’ve seen 3.7.0.
However official expected url, you explicitly mentioned in issue is https://docs.builbot.net/current
says 3.6.0.
On https://docs.buildbot.net/ I see that latest published documentation is 3.6.0, so there is missing documentation for 3.6.1 and 3.7.0.

I see in bbdocs repo that  there is 3.7.0 latest committed version [https://github.com/buildbot/bbdocs/commits/master](https://github.com/buildbot/bbdocs/commits/master).
So I assume there is issue on deployment/publishing  side of  buildbot.net site.

**Comment by p12tic** [comment]
Fixed now.

**Comment by YngveNPettersen** [comment]
It seems there is still an issue with updating the documentation. https://docs.buildbot.net/current/index.html is currently for v3.9, while the released version is 3.11
