### ISSUE TITLE
react ui: NestedParameter not displayed

### ISSUE THREAD

**Issue by Gvgeorge** [buildbot/buildbot#7624]
![image](https://github.com/buildbot/buildbot/assets/68271668/c00b8df8-f03a-448c-939b-0a0d52b82e9a)

React UI does not display NestedParameters in the force build creation form. Tried on Chrome and Edge, on Windows.

**Comment by tdesveaux** [comment]
Fixed in master by #7571

**Comment by Gvgeorge** [comment]
Not entirely fixed it seems.
The issue only happens with "tabs" layout, simple and vertical work fine
![image](https://github.com/user-attachments/assets/a0a64bdf-d9bd-4fc1-a7cf-0cb025c2f6d4)
