### ISSUE TITLE
util.BooleanParameter checkbox is not checked in UI when default=True

### ISSUE THREAD

**Issue by vit9696** [buildbot/buildbot#7773]
For the following code snippet:

```py
    param_test = util.BooleanParameter(
        name='is_test',
        label="Enable test (uncheck for no test)",
        default=True,
    )
```

The form will not have `is_test` checkbox enabled when running the plan. It will be disabled and will result in `null` in the plan properties. This is a regression somewhere in late 3.x or 4.0. Possibly also caused by React view.

**Comment by tdesveaux** [comment]
Same as #7772, was fixed by #7571, but not backported.

**Comment by vit9696** [comment]
I have just upgraded to 4.0.2, yet the issue is still present.

**Comment by tdesveaux** [comment]
https://github.com/buildbot/buildbot/pull/7832 backported the fix, but only applied it to `react-base` and not `base`.

@vit9696 using the `base_react` www plugin should fix the issue for you (you'll need to install the `buildbot-www-react` python package).

```python
c["www"] = {
    "port": 8010,
    "plugins": {"base_react": True},
}
```

**Comment by vit9696** [comment]
* `base_react` plugin is deprecated, while we can migrate back to it, it will disappear sooner or later.
* `base_react` plugin does not work correctly either: when multiple entries are selected, clicking on one results in this entry being deselected, instead of becoming the only selected one. This violates the standard select behaviour: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple

**Comment by pp1e** [comment]
Have the same problem on 4.0.2 version

**Comment by vit9696** [comment]
Tested, still broken on 4.0.3.

**Comment by vit9696** [comment]
Tested, works on 4.1.0. Most likely 4.0.x is still broken.
